/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veterinarios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static veterinarios.frmReporte.isValidDate;

/**
 *
 * @author jcami
 */
public class frmFrecuencias extends javax.swing.JFrame {

    /**
     * Creates new form frmFrecuencias
     */
    DefaultTableModel tableModel;
    TableRowSorter<DefaultTableModel> sorter;
    infoConexion con;

    public frmFrecuencias() {
        initComponents();
        con = new infoConexion();
        lbTratamientos.setVisible(false);
        comboTratamientos.setVisible(false);
        btnBuscar.setVisible(false);

        setTitle("Admin");

        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"Documento", "Nombre", "Frecuencia"});
        mostrarClientes();

        sorter = new TableRowSorter<>(tableModel);

    }

    private void filtrarTabla() {
        String consulta = comboTratamientos.getSelectedItem().toString().trim().toLowerCase();

        RowFilter<DefaultTableModel, Object> filter = new RowFilter<DefaultTableModel, Object>() {
            @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Object> entry) {
                String valorTabla = entry.getStringValue(0).trim().toLowerCase();
                String consulta = comboTratamientos.getSelectedItem().toString().trim().toLowerCase();
                System.out.println("Valor en tabla (Tipo Animal): " + valorTabla + ", Consulta (Combo): " + consulta);
                boolean coincideConsulta = consulta.equals("seleccione...") || valorTabla.equals(consulta);
                return coincideConsulta;
            }
        };

        sorter.setRowFilter(filter);
        if (sorter.getViewRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Campos no encontrados",
                    "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
            comboTratamientos.setSelectedIndex(0);
            filtrarTabla();
        } 
    }

    public void mostrarClientes() {

        try {

            Connection connection = DriverManager.getConnection(con.getUrl(), con.getUsername(), con.getPassword());

            PreparedStatement statement = connection.prepareStatement("call ReporteFrecuenciaClientes()");
            ResultSet ps = statement.executeQuery();
            ResultSetMetaData metaData = ps.getMetaData();

            while (ps.next()) {

                Object[] filas = new Object[metaData.getColumnCount()];
                for (int i = 0; i < metaData.getColumnCount(); i++) {
                    filas[i] = ps.getObject(i + 1);
                }
                tableModel.addRow(filas);
            }

            ps.close();
            statement.close();
            connection.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la consulta");
            System.out.println(ex);

        }

    }

    public void mostrar() {

        try {

            Connection connection = DriverManager.getConnection(con.getUrl(), con.getUsername(), con.getPassword());

            PreparedStatement statement = connection.prepareStatement("call ReporteTratamientos()");
            ResultSet ps = statement.executeQuery();
            ResultSetMetaData metaData = ps.getMetaData();

            while (ps.next()) {

                Object[] filas = new Object[metaData.getColumnCount()];
                for (int i = 0; i < metaData.getColumnCount(); i++) {
                    filas[i] = ps.getObject(i + 1);
                }
                tableModel.addRow(filas);
            }

            ps.close();
            statement.close();
            connection.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la consulta");
            System.out.println(ex);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        lbTratamientos = new javax.swing.JLabel();
        comboTratamientos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFrecuencias = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("VitalVet-Reporte Frecuencias");

        btnConsulta.setText("Tratamientos");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        lbTratamientos.setText("Tipo Animal");

        comboTratamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Canino", "Felino", "Lagomorfo", "Roedor", "Ave", "Reptil" }));

        tbFrecuencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbFrecuencias);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClientes)
                        .addGap(29, 29, 29)
                        .addComponent(btnConsulta)
                        .addGap(30, 30, 30)
                        .addComponent(lbTratamientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta)
                    .addComponent(btnClientes)
                    .addComponent(lbTratamientos)
                    .addComponent(comboTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        lbTratamientos.setVisible(false);
        comboTratamientos.setVisible(false);
        btnBuscar.setVisible(false);
        tableModel.setColumnIdentifiers(new String[]{"Documento", "Nombre", "Frecuencia"});
        tbFrecuencias.setVisible(true);
        mostrarClientes();
        tbFrecuencias.setModel(tableModel);

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed

        lbTratamientos.setVisible(true);
        comboTratamientos.setVisible(true);
        btnBuscar.setVisible(true);

        DefaultTableModel modeloReporteTratamientos = new DefaultTableModel();
        modeloReporteTratamientos.setColumnIdentifiers(new String[]{"tipoMascota", "Tratamiento", "Frecuencia"});
        tbFrecuencias.setModel(modeloReporteTratamientos);

        tableModel = modeloReporteTratamientos;

        mostrar();

        sorter = new TableRowSorter<>(tableModel);
        tbFrecuencias.setRowSorter(sorter);

    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        filtrarTabla();

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFrecuencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFrecuencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFrecuencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFrecuencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFrecuencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JComboBox<String> comboTratamientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTratamientos;
    private javax.swing.JTable tbFrecuencias;
    // End of variables declaration//GEN-END:variables
}
