/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veterinarios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Veterinaria1 extends javax.swing.JFrame {

    /**
     * Creates new form Veterinaria1
     */
    frmReporte ventanareporte;
    frmLogin login;

    DefaultTableModel reporteTableModel;
    ArrayList<Consultas> listadoConsultas;
    ArrayList<Pacientes> listadoPacientes;
    infoConexion con;

    String user;
    int idUser;
    int idProfile;
    double valorTotal = 0;

    public Veterinaria1(String user, int iduser, int idprofile) {

        initComponents();
        valorTotal = 0;

        this.user = user.replace(" ", "");
        this.idUser = iduser;
        this.idProfile = idprofile;

        lblUser.setText("User:" + this.user.toUpperCase());

        ventanareporte = new frmReporte(this.user, this.idUser, this.idProfile);
        listadoConsultas = new ArrayList<>() {
            {
                add(new Consultas("Consulta de Rutina", 90000.0));
                add(new Consultas("Consulta de Diagnostico", 150000.0));
                add(new Consultas("Consulta de Especialidad", 300000.0));
                add(new Consultas("Hospitalizacion", 400000.0));
                add(new Consultas("Peluqueria y Baño", 60000.0));
                add(new Consultas("Adiestramiento", 110000.0));
                add(new Consultas("Preventiva", 70000.0));
            }
        };
        listadoPacientes = new ArrayList<>() {
            {
                add(new Pacientes("Canino(perros).", 0.07));
                add(new Pacientes("Felino(gatos).", 0.08));
                add(new Pacientes("Lagomorfo(conejos).", 0.10));
                add(new Pacientes("Roedor(hámsters, ratas", 0.12));
                add(new Pacientes("Ave(loros, periquitos, canarios, etc.).", 0.09));
                add(new Pacientes("Reptil(tortugas, lagartos, serpientes).", 0.15));
            }
        };

        con = new infoConexion();
        reporteTableModel = ventanareporte.tableModel;

        atxtObservaciones.setLineWrap(true);
        atxtObservaciones.setWrapStyleWord(true);
        setResizable(false);
        setTitle("VitalVet");
        txtNombreCliente.setText("");
        txtNombrePaciente.setText("");
        txtDocumento.setText("");

    }

    public void llenarCombos() {
        comboConsulta.removeAllItems();
        comboPacientes.removeAllItems();
        comboConsulta.addItem("Seleccione...");
        comboPacientes.addItem("Seleccione...");
        for (int i = 0; i < listadoConsultas.size(); i++) {
            comboConsulta.addItem(listadoConsultas.get(i).getTipoconsulta());

        }
        for (int i = 0; i < listadoPacientes.size(); i++) {
            comboPacientes.addItem(listadoPacientes.get(i).getTipoPaciente());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboVeterinario = new javax.swing.JComboBox<>();
        comboPacientes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        atxtObservaciones = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        txtNombrePaciente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboConsulta = new javax.swing.JComboBox<>();
        lblUser = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel1.setText("VitalVet  -  Latidos De Salud.");

        jLabel2.setText("Paciente");

        jLabel3.setText("Veterinario");

        jLabel4.setText("Cliente");

        jLabel5.setText("TipoPaciente");

        comboVeterinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Dra. Patty Pata", "Raúl Mora", "Dra. Felicia Lame", "Dr. Bernardo Cura", "Margarita Pica" }));

        comboPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Canino (perros).", "Felino (gatos).", "Lagomorfo (conejos).", "Roedor (hámsters,ratas).", "Ave (loros, periquitos, canarios, etc.).", "Reptil (tortugas, lagartos, serpientes)." }));

        jLabel6.setText("Observaciones");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        atxtObservaciones.setColumns(20);
        atxtObservaciones.setRows(5);
        jScrollPane2.setViewportView(atxtObservaciones);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        txtNombrePaciente.setText("jTextField1");

        txtNombreCliente.setText("jTextField2");

        jLabel7.setText("TipoConsulta");

        comboConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Consulta de Rutina", "Consulta de Diagnóstico", "Consulta de Especialidad", "Consulta Preventiva", "Hospitalización", "Peluquería", "Adiestramiento", " " }));

        lblUser.setText("--");

        jLabel9.setText("documento");

        txtDocumento.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNombrePaciente)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(txtDocumento, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboPacientes, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(comboVeterinario, 0, 153, Short.MAX_VALUE)
                                    .addComponent(comboConsulta, 0, 1, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 132, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(102, 102, 102)
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnReporte))
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed

        ventanareporte.setVisible(true);


    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtNombreCliente.getText().isEmpty()
                && !txtDocumento.getText().isEmpty()
                && !txtNombrePaciente.getText().isEmpty()
                && comboConsulta.getSelectedIndex() > 0
                && comboPacientes.getSelectedIndex() > 0
                && comboVeterinario.getSelectedIndex() > 0) {
            int indicePaciente = comboPacientes.getSelectedIndex() - 1;
            int indiceConsulta = comboConsulta.getSelectedIndex() - 1;

            double valorpaciente = listadoPacientes.get(indicePaciente).getValor();
            double valorconsulta = listadoConsultas.get(indiceConsulta).getPrecioConsulta();
            valorTotal = valorconsulta + (valorconsulta * valorpaciente);
            int respuesta = JOptionPane.showConfirmDialog(
                    null,
                    "¿Deseas guardar la consulta con un valor de: $" + valorTotal + "?",
                    "Confirmar Guardado",
                    JOptionPane.YES_NO_OPTION);

            switch (respuesta) {
                case JOptionPane.YES_OPTION:
                    Guardar();
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "El guardado ha sido cancelado.");
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error Campos Vacios");
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       if(idProfile==2){
        login = new frmLogin();
        login.setVisible(true);
        ventanareporte.dispose();}else{
       this.dispose();
       }
    }//GEN-LAST:event_formWindowClosed

    public void Guardar() {
        try {

            Connection connection = DriverManager.getConnection(con.getUrl(),
                    con.getUsername(), con.getPassword());
            PreparedStatement stmt = connection.prepareStatement("call InsertarConsulta (?,?,?, ?, ?,?, ?, ?)");

            stmt.setInt(1, comboVeterinario.getSelectedIndex());
            stmt.setString(2, txtDocumento.getText());
            stmt.setString(3, txtNombreCliente.getText());
            stmt.setString(4, txtNombrePaciente.getText());
            stmt.setInt(5, comboPacientes.getSelectedIndex());
            stmt.setInt(6, comboConsulta.getSelectedIndex());
            stmt.setDouble(7, valorTotal);
            stmt.setString(8, atxtObservaciones.getText());

            stmt.executeUpdate();

            stmt.close();
            connection.close();
            JOptionPane.showMessageDialog(rootPane, "Guardado con exito");
        } catch (SQLException ex) {

            System.out.println(ex);
            JOptionPane.showMessageDialog(rootPane, "Error");
        }

        txtNombreCliente.setText("");
        txtNombrePaciente.setText("");
        txtDocumento.setText("");

        atxtObservaciones.setText("");
        comboConsulta.setSelectedIndex(0);
        comboPacientes.setSelectedIndex(0);
        comboVeterinario.setSelectedIndex(0);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veterinaria1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veterinaria1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veterinaria1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veterinaria1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veterinaria1(null, 0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxtObservaciones;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> comboConsulta;
    private javax.swing.JComboBox<String> comboPacientes;
    private javax.swing.JComboBox<String> comboVeterinario;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
